---
- name: Remove previous version [{{ ansible_os_family }}]
  apt:
    name: '{{ item }}'
    state: removed
    force: yes
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - docker
    - docker-engine
    - docker.io
  become: true

- name: Determine revision
  raw: "echo -n `uname -r`"
  register: revision
  ignore_errors: yes

- debug:
    var: revision.stdout

- name: Install dependencies [{{ ansible_os_family }}]
  apt:
    name: '{{ item }}'
    state: installed
    force: yes
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - linux-image-extra-virtual
    - linux-image-extra-{{ revision.stdout }}
  become: true

- name: Add key
  raw: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Add docker repository
  become: true
  lineinfile:
    line: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    dest: /etc/apt/sources.list.d/docker.list
    state: present
    create: yes