---
- name: Remove previous version [{{ ansible_os_family }}]
  apt:
    name: '{{ item }}'
    state: removed
    force: true
    update_cache: true
    cache_valid_time: 3600
  with_items:
    - docker
    - docker-engine
    - docker.io
  become: true

- name: Determine revision
  raw: "echo -n `uname -r`"
  register: revision
  ignore_errors: true

- name: Install dependencies [{{ ansible_os_family }}]
  apt:
    name: '{{ item }}'
    state: installed
    force: true
    update_cache: true
    cache_valid_time: 3600
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - linux-image-extra-virtual
    - linux-image-extra-{{ revision.stdout }}
  become: true
  ignore_errors: true

- name: Add key
  raw: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Add docker repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present
  become: true
