---
language: python
python: "2.7"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: xenial
      sudo: required

addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install -U pip
  - pip install -U ansible

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory
