---
language: python
python: "2.7"

matrix:
  include:
    - os: ubuntu
      dist: trusty
      sudo: required
    - os: ubuntu
      dist: xenial
      sudo: required
    - os: centos
      dist: 6
      sudo: required
    - os: rhel
      dist: 6
      sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # OS
  - uname -a

  # Install ansible
  - pip install -U pip
  - pip install -U ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/