---
- name: Install docker-ce [{{ ansible_os_family }}]
  yum:
    name: '{{ item }}'
    state: installed
    update_cache: true
  with_items:
      - docker-ce
  become: true
  notify: restart docker
