---
- include: dependencies/apt.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: dependencies/yum.yml
  when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon" or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install docker-ce APT
  apt:
    name: '{{ item }}'
    state: installed
    force: yes
    update_cache: yes
    cache_valid_time: 3600
  with_items:
      - docker-ce
  become: true
  notify: restart docker
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install docker-ce YUM
  yum:
    name: '{{ item }}'
    state: installed
    force: yes
    update_cache: yes
    cache_valid_time: 3600
  with_items:
      - docker-ce
  become: true
  notify: restart docker
  when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon" or ansible_distribution == 'Red Hat Enterprise Linux'
