---
- import_tasks: dependencies/apt.yml
  when: ansible_os_family == 'Debian'

- import_tasks: dependencies/yum.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: install/apt.yml
  when: ansible_os_family == 'Debian'

- import_tasks: install/yum.yml
  when: ansible_os_family == 'RedHat'
