---
- name: Initial setup
  hosts: vagrant
  gather_facts: no

  roles:
    - { role: ../ansible-role-docker-ce/vagrant/initial }

- name: Role test [docker-ce]
  hosts: vagrant

  roles:
    - { role: ../ansible-role-docker-ce }
